// File generated by flutterfire configure
// This is a placeholder. Run `flutterfire configure` to generate the real file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyCjm71pymZGqb1VAOz5touBtAeovCEZbko',
        appId: '1:308400008276:web:4b965b80d9b3a93a3651c1',
        messagingSenderId: '308400008276',
        projectId: 'kheti-bari-d0309',
        authDomain: 'kheti-bari-d0309.firebaseapp.com',
        storageBucket: 'kheti-bari-d0309.firebasestorage.app',
        measurementId: 'G-XXCEPCSPQ8',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // TODO: Replace with your Android config
        return const FirebaseOptions(
          apiKey: 'YOUR_ANDROID_API_KEY',
          appId: 'YOUR_ANDROID_APP_ID',
          messagingSenderId: 'YOUR_SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
        );
      case TargetPlatform.iOS:
        // TODO: Replace with your iOS config
        return const FirebaseOptions(
          apiKey: 'YOUR_IOS_API_KEY',
          appId: 'YOUR_IOS_APP_ID',
          messagingSenderId: 'YOUR_SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
          storageBucket: 'YOUR_PROJECT_ID.appspot.com',
          iosBundleId: 'YOUR_IOS_BUNDLE_ID',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

